theme: null
title: tollef.web
email: tollefj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  random notes and ramblings
baseurl: ""
future: true
# the subpath of your site, e.g. /blog
url: "https://tollefj.github.io/"
twitter_username:
github_username:  tollefj

linkedin_url: "https://www.linkedin.com/in/tollefj/"
github_url: "https://github.com/tollefj"

markdown: kramdown  
highlighter: rouge 
kramdown:
  syntax_highlighter_opts:
    line_numbers: true  
    span: true           
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge  # Ensure this is set
  syntax_highlighter_opts:
    guess_lang: false


# permalink: /:categories/:title/
permalink: /:title/

paginate: 5
# paginate_path: "/page:num/"
plugins:
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/searchData.json

lunr_settings:
  atozsortfield: title
  collections: [posts]
  displayfields:
  - {field: title, headerfield: true, highlight: true}
  - {field: categories, headerimage: false, highlight: false}
  - {field: description, label: Description, highlight: false}
  fuzzysearchfields: [title]
  view_facets: 5
