theme: null
title: tollef.web
email: tollefj@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  random notes and ramblings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  tollefj

markdown: kramdown  
highlighter: rouge 
kramdown:
  syntax_highlighter_opts:
    line_numbers: true  
    span: true           
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge  # Ensure this is set
  syntax_highlighter_opts:
    guess_lang: false


paginate: 5
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
